# Generated by Django 5.2.5 on 2025-12-17 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_remove_institution_unique"),
        ("credit_cards", "0002_alter_creditcard__security_code"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Visualização"),
                            ("create", "Criação"),
                            ("update", "Atualização"),
                            ("delete", "Exclusão"),
                            ("reveal", "Revelação de Senha/Credencial"),
                            ("download", "Download de Arquivo"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("failed_login", "Tentativa de Login Falha"),
                            ("other", "Outro"),
                        ],
                        max_length=100,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
                ("object_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Atividade",
                "verbose_name_plural": "Logs de Atividades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("personal", "Pessoal"),
                            ("financial", "Financeiro"),
                            ("legal", "Jurídico"),
                            ("medical", "Médico"),
                            ("tax", "Impostos"),
                            ("work", "Trabalho"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                (
                    "archive_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("pdf", "PDF"),
                            ("image", "Imagem"),
                            ("document", "Documento"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "_encrypted_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto Criptografado"
                    ),
                ),
                (
                    "encrypted_file",
                    models.FileField(
                        blank=True, null=True, upload_to="security/archives/%Y/%m/"
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("tags", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archives",
                        to="members.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo Confidencial",
                "verbose_name_plural": "Arquivos Confidenciais",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Password",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "site",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Site"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=200, verbose_name="Usuário/Email"),
                ),
                ("_password", models.TextField(verbose_name="Senha (Criptografada)")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("social", "Redes Sociais"),
                            ("email", "E-mail"),
                            ("banking", "Bancário"),
                            ("work", "Trabalho"),
                            ("entertainment", "Entretenimento"),
                            ("shopping", "Compras"),
                            ("streaming", "Streaming"),
                            ("gaming", "Games"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("last_password_change", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passwords",
                        to="members.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Senha",
                "verbose_name_plural": "Senhas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoredBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome da Conta"),
                ),
                (
                    "institution_name",
                    models.CharField(
                        max_length=200, verbose_name="Instituição Financeira"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CC", "Conta Corrente"),
                            ("CS", "Conta Salário"),
                            ("CP", "Conta Poupança"),
                            ("CI", "Conta Investimento"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "_account_number",
                    models.TextField(verbose_name="Número da Conta (Criptografado)"),
                ),
                ("agency", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "_password",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Senha Bancária (Criptografada)",
                    ),
                ),
                (
                    "_digital_password",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Senha Digital (Criptografada)",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "finance_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stored_credentials",
                        to="accounts.account",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stored_bank_accounts",
                        to="members.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Bancária Armazenada",
                "verbose_name_plural": "Contas Bancárias Armazenadas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoredCreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome do Cartão"),
                ),
                (
                    "_card_number",
                    models.TextField(verbose_name="Número do Cartão (Criptografado)"),
                ),
                (
                    "_security_code",
                    models.TextField(verbose_name="CVV (Criptografado)"),
                ),
                (
                    "expiration_month",
                    models.IntegerField(verbose_name="Mês de Validade"),
                ),
                (
                    "expiration_year",
                    models.IntegerField(verbose_name="Ano de Validade"),
                ),
                (
                    "cardholder_name",
                    models.CharField(max_length=200, verbose_name="Nome do Titular"),
                ),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("MSC", "Mastercard"),
                            ("VSA", "Visa"),
                            ("ELO", "Elo"),
                            ("EXP", "American Express"),
                            ("HCD", "Hipercard"),
                            ("DIN", "Diners Club"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="Bandeira",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "finance_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stored_credentials",
                        to="credit_cards.creditcard",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stored_credit_cards",
                        to="members.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartão Armazenado",
                "verbose_name_plural": "Cartões Armazenados",
                "ordering": ["-created_at"],
            },
        ),
    ]
