# Generated by Django 5.2.5 on 2025-12-17 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "Visualização"),
                    ("create", "Criação"),
                    ("update", "Atualização"),
                    ("delete", "Exclusão"),
                    ("reveal", "Revelação de Senha/Credencial"),
                    ("download", "Download de Arquivo"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("failed_login", "Tentativa de Login Falha"),
                    ("other", "Outro"),
                ],
                max_length=100,
                verbose_name="Ação",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="description",
            field=models.TextField(
                help_text="Descrição detalhada da ação realizada",
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP de origem da requisição",
                null=True,
                verbose_name="Endereço IP",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="model_name",
            field=models.CharField(
                blank=True,
                help_text="Nome do modelo afetado (ex: Password, StoredCreditCard)",
                max_length=100,
                null=True,
                verbose_name="Modelo",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="object_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID do objeto afetado",
                null=True,
                verbose_name="ID do Objeto",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="Informações do navegador/cliente",
                max_length=500,
                null=True,
                verbose_name="User Agent",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "action"], name="security_ac_user_id_08221b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["created_at"], name="security_ac_created_4ec062_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="security_ac_model_n_ad4815_idx",
            ),
        ),
    ]
