# Generated by Django 5.2.5 on 2025-12-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="payed",
            field=models.BooleanField(default=False, verbose_name="Pago"),
        ),
    ]
