# Generated by Django 5.2.5 on 2026-01-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_add_credit_card_to_fixed_expense"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="fixedexpense",
            new_name="expenses_fi_credit__e7c779_idx",
            old_name="expenses_fi_credit__idx",
        ),
    ]
