# Generated by Django 5.2.5 on 2026-01-19 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_institution_unique"),
        ("credit_cards", "0005_migrate_expenses_to_purchases"),
        (
            "expenses",
            "0007_rename_expenses_fi_credit__idx_expenses_fi_credit__e7c779_idx",
        ),
        ("loans", "0001_initial"),
        ("members", "0001_initial"),
        ("transfers", "0004_link_existing_transfer_transactions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="related_bill_payment",
            field=models.ForeignKey(
                blank=True,
                help_text="Fatura de cartão de crédito que esta despesa está pagando",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_expenses",
                to="credit_cards.creditcardbill",
                verbose_name="Fatura de Cartão Relacionada",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["related_bill_payment"], name="expenses_ex_related_4d6ad5_idx"
            ),
        ),
    ]
