# Generated by Django 5.2.5 on 2026-01-22 17:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_add_overdraft_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('description', models.CharField(help_text='Nome ou descrição do cofre', max_length=200, verbose_name='Descrição')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo atual do cofre (incluindo rendimentos)', max_digits=15, verbose_name='Saldo Atual')),
                ('accumulated_yield', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de rendimentos acumulados', max_digits=15, verbose_name='Rendimentos Acumulados')),
                ('yield_rate', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Taxa de rendimento diária (ex: 0.000329 = 0.0329% ao dia)', max_digits=10, verbose_name='Taxa de Rendimento')),
                ('last_yield_date', models.DateField(blank=True, help_text='Data em que o último rendimento foi calculado', null=True, verbose_name='Data do Último Rendimento')),
                ('is_active', models.BooleanField(default=True, help_text='Se o cofre está ativo e aceitando operações', verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('account', models.ForeignKey(help_text='Conta bancária associada a este cofre', on_delete=django.db.models.deletion.PROTECT, related_name='vaults', to='accounts.account', verbose_name='Conta Associada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Cofre',
                'verbose_name_plural': 'Cofres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('description', models.CharField(help_text='Nome ou descrição da meta', max_length=200, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('savings', 'Poupança'), ('investment', 'Investimento'), ('emergency', 'Reserva de Emergência'), ('travel', 'Viagem'), ('education', 'Educação'), ('property', 'Imóvel'), ('vehicle', 'Veículo'), ('retirement', 'Aposentadoria'), ('health', 'Saúde'), ('other', 'Outro')], default='savings', max_length=50, verbose_name='Categoria')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Valor que se deseja atingir', max_digits=15, verbose_name='Valor Alvo')),
                ('target_date', models.DateField(blank=True, help_text='Data prevista para atingir a meta', null=True, verbose_name='Data Alvo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('vaults', models.ManyToManyField(blank=True, help_text='Cofres que contribuem para esta meta', related_name='goals', to='vaults.vault', verbose_name='Cofres Associados')),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Depósito'), ('withdrawal', 'Saque'), ('yield', 'Rendimento')], max_length=20, verbose_name='Tipo de Transação')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Após Transação')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Transação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='vaults.vault', verbose_name='Cofre')),
            ],
            options={
                'verbose_name': 'Transação do Cofre',
                'verbose_name_plural': 'Transações do Cofre',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['account', 'is_active'], name='vaults_vaul_account_092fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['is_active', 'is_deleted'], name='vaults_vaul_is_acti_cac4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['is_active', 'is_completed'], name='vaults_fina_is_acti_00d652_idx'),
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['category'], name='vaults_fina_categor_e5da87_idx'),
        ),
        migrations.AddIndex(
            model_name='vaulttransaction',
            index=models.Index(fields=['vault', 'transaction_type'], name='vaults_vaul_vault_i_d8b6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='vaulttransaction',
            index=models.Index(fields=['transaction_date'], name='vaults_vaul_transac_ad18fc_idx'),
        ),
    ]
