# Generated by Django 5.2.5 on 2025-12-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="_security_code",
            field=models.TextField(
                help_text="Campo criptografado para armazenar o CVV",
                verbose_name="Código de Segurança (Criptografado)",
            ),
        ),
    ]
