# Generated by Django 5.2.5 on 2026-01-16 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_cards", "0003_alter_creditcardexpense_value"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditcardexpense",
            options={
                "ordering": ["-id"],
                "verbose_name": "Despesa de Cartão (Legado)",
                "verbose_name_plural": "Despesas de Cartão (Legado)",
            },
        ),
        migrations.CreateModel(
            name="CreditCardPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total da compra",
                        max_digits=12,
                        verbose_name="Valor Total",
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="Data da Compra")),
                ("purchase_time", models.TimeField(verbose_name="Horário da Compra")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food and drink", "Comida e bebida"),
                            ("bills and services", "Contas e serviços"),
                            ("electronics", "Eletrônicos"),
                            ("family and friends", "Amizades e Família"),
                            ("pets", "Animais de estimação"),
                            ("digital signs", "Assinaturas digitais"),
                            ("house", "Casa"),
                            ("purchases", "Compras"),
                            ("donate", "Doações"),
                            ("education", "Educação"),
                            ("loans", "Empréstimos"),
                            ("entertainment", "Entretenimento"),
                            ("taxes", "Impostos"),
                            ("investments", "Investimentos"),
                            ("others", "Outros"),
                            ("vestuary", "Roupas"),
                            ("health and care", "Saúde e cuidados pessoais"),
                            ("professional services", "Serviços profissionais"),
                            ("supermarket", "Supermercado"),
                            ("rates", "Taxas"),
                            ("transport", "Transporte"),
                            ("travels", "Viagens"),
                        ],
                        max_length=200,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "total_installments",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantidade de Parcelas"
                    ),
                ),
                (
                    "merchant",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Estabelecimento",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="credit_cards/receipts/",
                        verbose_name="Comprovante",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="credit_cards.creditcard",
                        verbose_name="Cartão",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.member",
                        verbose_name="Membro Responsável",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra de Cartão",
                "verbose_name_plural": "Compras de Cartão",
                "ordering": ["-purchase_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CreditCardInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveIntegerField(verbose_name="Número da Parcela"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor da Parcela"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data de Vencimento")),
                ("payed", models.BooleanField(default=False, verbose_name="Paga")),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installments",
                        to="credit_cards.creditcardbill",
                        verbose_name="Fatura",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="credit_cards.creditcardpurchase",
                        verbose_name="Compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcela de Cartão",
                "verbose_name_plural": "Parcelas de Cartão",
                "ordering": ["purchase", "installment_number"],
            },
        ),
        migrations.AddIndex(
            model_name="creditcardpurchase",
            index=models.Index(
                fields=["-purchase_date"], name="credit_card_purchas_fe18ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditcardpurchase",
            index=models.Index(
                fields=["card", "-purchase_date"], name="credit_card_card_id_7dd83f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditcardpurchase",
            index=models.Index(
                fields=["category", "-purchase_date"],
                name="credit_card_categor_ed5742_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creditcardinstallment",
            index=models.Index(
                fields=["bill", "payed"], name="credit_card_bill_id_62af89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditcardinstallment",
            index=models.Index(
                fields=["due_date"], name="credit_card_due_dat_1f23e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditcardinstallment",
            index=models.Index(
                fields=["purchase", "installment_number"],
                name="credit_card_purchas_e569d0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditcardinstallment",
            constraint=models.UniqueConstraint(
                fields=("purchase", "installment_number"),
                name="unique_purchase_installment",
            ),
        ),
    ]
