# Generated by Django 5.2.5 on 2026-01-10 (custom migration)

from django.db import migrations, models
import pgvector.django


def clear_embeddings(apps, schema_editor):
    """Clear all existing embeddings before changing dimensions."""
    ContentEmbedding = apps.get_model('ai_assistant', 'ContentEmbedding')
    # Set all embeddings to None to avoid dimension mismatch
    ContentEmbedding.objects.update(
        embedding=None,
        is_indexed=False,
        indexed_at=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        # First, clear all embeddings
        migrations.RunPython(
            clear_embeddings,
            reverse_code=migrations.RunPython.noop
        ),
        # Then alter the field dimensions
        migrations.AlterField(
            model_name='contentembedding',
            name='embedding',
            field=pgvector.django.VectorField(
                blank=True,
                dimensions=384,
                null=True,
                verbose_name='Vetor de Embedding'
            ),
        ),
        # Update default model name
        migrations.AlterField(
            model_name='contentembedding',
            name='embedding_model',
            field=models.CharField(
                default='all-MiniLM-L6-v2',
                max_length=100,
                verbose_name='Modelo de Embedding'
            ),
        ),
    ]
